{{- if and .Values.auth.enabled .Values.auth.token (not .Values.auth.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "talos-ai-operator.authSecretName" . }}
  labels:
    {{- include "talos-ai-operator.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.token | quote }}
{{- end }}
