#!/usr/bin/env python3
"""
remediate.py — Chapter 5: autonomous remediation through GitOps.

This is the ONLY state-changing script in talos-sre, and it changes *git*, not
the cluster: it generates a fix manifest, commits it to a branch in the Gitea
`platform` repo (the GitOps source of truth), and opens a PR. ArgoCD reconciles
the change only after a human merges — the cluster is never touched directly.

Supported fixes (MVP):
  * missing-pdb     — add a PodDisruptionBudget for a single-replica workload
  * (extend by dropping a new generator into FIXES)

Guardrails: dry-run by default (prints the manifest + the git/PR commands);
`--apply` is required to actually push and open the PR, and it re-confirms.

    # preview only
    python3 remediate.py --cluster admin@workload-1 --fix missing-pdb \
        --namespace demo --workload web
    # actually open the PR
    python3 remediate.py --cluster admin@workload-1 --fix missing-pdb \
        --namespace demo --workload web --apply
"""
from __future__ import annotations

import argparse
import subprocess
import sys
import urllib.request
import urllib.error
import json
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from prerequisites import enforce  # noqa: E402

# Gitea hub coordinates (match spikes/talos-gitops/scripts/lib.sh).
GITEA_USER = "gitops"
GITEA_PASS = "gitops-admin-123"
GITEA_REPO = "platform"
GITEA_LOCAL = "http://localhost:3000"  # via `kubectl port-forward svc/gitea-http`


def _die(msg: str) -> None:
    print(msg, file=sys.stderr)
    sys.exit(1)


def fix_missing_pdb(ns: str, workload: str) -> tuple[str, str]:
    """Return (repo_path, manifest) for a PodDisruptionBudget fix."""
    path = f"gitops/apps/remediation/{ns}-{workload}-pdb.yaml"
    manifest = f"""# Auto-generated by talos-sre remediate.py
# Fixes: single-replica workload {ns}/{workload} had no PodDisruptionBudget.
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {workload}-pdb
  namespace: {ns}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {workload}
"""
    return path, manifest


FIXES = {"missing-pdb": fix_missing_pdb}


def gitea_open_pr(branch: str, title: str, body: str) -> None:
    url = f"{GITEA_LOCAL}/api/v1/repos/{GITEA_USER}/{GITEA_REPO}/pulls"
    data = json.dumps({"head": branch, "base": "main", "title": title, "body": body}).encode()
    auth = subprocess.run(["printf", f"{GITEA_USER}:{GITEA_PASS}"], capture_output=True, text=True).stdout
    import base64
    tok = base64.b64encode(auth.encode()).decode()
    req = urllib.request.Request(url, data=data, method="POST",
                                 headers={"Content-Type": "application/json",
                                          "Authorization": f"Basic {tok}"})
    try:
        with urllib.request.urlopen(req) as r:
            resp = json.loads(r.read())
            print(f"  PR opened: {resp.get('html_url', resp.get('url'))}")
    except urllib.error.HTTPError as e:
        _die(f"Gitea PR creation failed ({e.code}): {e.read().decode()}")


def main() -> None:
    p = argparse.ArgumentParser(description="GitOps remediation (opens a PR)")
    p.add_argument("--cluster", required=True, help="cluster the finding came from (for the PR description)")
    p.add_argument("--fix", required=True, choices=list(FIXES))
    p.add_argument("--namespace", required=True)
    p.add_argument("--workload", required=True)
    p.add_argument("--apply", action="store_true", help="actually push + open the PR (default: preview only)")
    args = p.parse_args()
    enforce(cluster=args.cluster, extra_binaries=["git", "kubectl"])

    path, manifest = FIXES[args.fix](args.namespace, args.workload)
    branch = f"remediate/{args.fix}-{args.namespace}-{args.workload}"
    title = f"fix({args.namespace}/{args.workload}): {args.fix}"
    body = (f"Auto-remediation proposed by **talos-sre** for a finding on "
            f"`{args.cluster}`.\n\nAdds `{path}`. ArgoCD will sync after merge.")

    print("== PROPOSED FIX MANIFEST")
    print(f"  path: {path}")
    print("  ---")
    print("\n".join("  " + l for l in manifest.splitlines()))
    print("\n== PLANNED ACTIONS (git changes only — never touches the cluster)")
    print("  1. port-forward Gitea:  kubectl --context admin@ops -n gitea port-forward svc/gitea-http 3000:3000")
    print(f"  2. clone {GITEA_LOCAL}/{GITEA_USER}/{GITEA_REPO}.git")
    print(f"  3. write {path} on branch {branch}, commit, push")
    print(f"  4. open PR -> base main  (title: {title})")

    if not args.apply:
        print("\n[dry-run] re-run with --apply to push the branch and open the PR.")
        sys.exit(0)

    # Real path: assumes `kubectl -n gitea port-forward svc/gitea-http 3000:3000`
    # is already running (the skill step opens it and shows the command first).
    print("\n[apply] confirm you want to push and open the PR (the cluster is NOT modified).")
    work = Path("/tmp") / f"talos-sre-{branch.replace('/', '-')}"
    subprocess.run(["rm", "-rf", str(work)], check=True)
    repo_url = f"http://{GITEA_USER}:{GITEA_PASS}@localhost:3000/{GITEA_USER}/{GITEA_REPO}.git"
    print(f"  $ git clone {GITEA_LOCAL}/{GITEA_USER}/{GITEA_REPO}.git {work}")
    if subprocess.run(["git", "clone", "-q", repo_url, str(work)]).returncode != 0:
        _die("clone failed — is `kubectl -n gitea port-forward svc/gitea-http 3000:3000` running?")
    target = work / path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(manifest)
    for cmd in (["git", "checkout", "-q", "-b", branch],
                ["git", "add", path],
                ["git", "-c", "user.email=talos-sre@example.com", "-c", "user.name=talos-sre",
                 "commit", "-q", "-m", title],
                ["git", "push", "-q", "-u", "origin", branch]):
        print("  $", " ".join(cmd))
        if subprocess.run(cmd, cwd=work).returncode != 0:
            _die(f"git step failed: {' '.join(cmd)}")
    gitea_open_pr(branch, title, body)
    print("\nDone. Review + merge the PR; ArgoCD reconciles the fix onto the cluster.")


if __name__ == "__main__":
    main()
